apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unit-test-task
spec:
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: test
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Running unit tests..."
        python -m nose tests
